global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'salary_prediction'
    static_configs:
      - targets: ['192.168.0.230:9001']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.0.230:9002']
